CREATE TABLE departments
( id number(30) NOT NULL,
  name varchar2(100) NOT NULL,
  head number(30),
  PRIMARY KEY (id)
);

CREATE TABLE staff
( id number(30) NOT NULL,
  full_name varchar2(100) NOT NULL,
  salary number(30),
  dep_id number(30),
  PRIMARY KEY (id)
);

ALTER TABLE departments
ADD CONSTRAINT fk_head
  FOREIGN KEY (head)
  REFERENCES staff(id);

ALTER TABLE staff
ADD CONSTRAINT fk_dep_id
  FOREIGN KEY (dep_id)
  REFERENCES departments(id);

CREATE SEQUENCE DEP_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_DEP
   BEFORE INSERT ON DEPARTMENTS
   FOR EACH ROW
   WHEN (NEW.ID IS NULL)
BEGIN
	:NEW.ID := DEP_SEQ.NEXTVAL;
END;

INSERT INTO DEPARTMENTS (NAME) VALUES ('DEP1');
INSERT INTO DEPARTMENTS (NAME) VALUES ('DEP2');
INSERT INTO DEPARTMENTS (NAME) VALUES ('DEP3');

CREATE SEQUENCE STAFF_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_STAFF
   BEFORE INSERT ON STAFF
   FOR EACH ROW
   WHEN (NEW.ID IS NULL)
BEGIN
	:NEW.ID := STAFF_SEQ.NEXTVAL;
END;

INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('AAA', 1, 100);
INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('BBB', 2, 150);
INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('CCC', 3, 130);

INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('DDD', 1, 115);
INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('EEE', 2, 127);
INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('FFF', 3, 149);

INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('GGG', 1, 137);
INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('HHH', 2, 124);
INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('III', 2, 111);

INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('JJJ', 3, 116);
INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('KKK', 3, 107);
INSERT INTO STAFF (FULL_NAME, DEP_ID, SALARY) VALUES ('LLL', 3, 112);

UPDATE DEPARTMENTS SET HEAD = 3 WHERE ID = 1;
UPDATE DEPARTMENTS SET HEAD = 6 WHERE ID = 2;
UPDATE DEPARTMENTS SET HEAD = 7 WHERE ID = 3;